<?php

namespace Application\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository 
extends EntityRepository
{
	public function findWithCredentialsLike ($trait)
	{
		return $this
			->createQueryBuilder('p')
			->addSelect('c')
			->leftJoin('p.credentials', 'c')
			->where('LOWER(CONCAT(c.nameFirst, \' \', c.nameLast)) LIKE LOWER(:trait)')
			->setParameter('trait', '%'.$trait.'%')
			->getQuery( )
			->getResult( )
		;
	}
}
