<section>
	<h3>Create contact.</h3>
	<?php foreach ($target->getCredentials( ) as $credentials): ?>
		<p><?php echo $credentials->getNameFirst( ); ?> <?php echo $credentials->getNameLast( ); ?></p>
	<?php endforeach ?>
	<?php
		if ($this->identity( ) != null)
		{
			if ($target->getId( ) != $this->identity( )->getPerson( )->getId( ))
			{
				$form->setData(array('id' => $target->getId( )));
		        $form->prepare( );
				echo $this->form()->openTag($form);
				echo $this->formRow($form->get('id'));
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
			} else {
				echo '<p>You can not contact with yourself.</p>';
			}
		} else {
			echo '<p>You have to authenticate to the system first.</p>';
		}
	?>
</section>