<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( ); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/layout.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <a href="<?php echo $this->url('application') ?>"><?php echo $this->translate('Home') ?></a>
            <a href="<?php echo $this->url('application', array('controller' => 'person', 'action' => 'find')) ?>"><?php echo $this->translate('Search') ?></a>
            <?php if($this->identity( ) == null): ?>
            <a href="<?php echo $this->url('application', array('controller' => 'account', 'action' => 'create')) ?>"><?php echo $this->translate('Signup') ?></a>
            <a href="<?php echo $this->url('application', array('controller' => 'account', 'action' => 'authenticate')) ?>"><?php echo $this->translate('Login') ?></a>
            <?php endif ?>
            <?php if($this->identity( ) != null): ?>
            <a href="<?php echo $this->url('application', array('controller' => 'person', 'action' => 'myself')) ?>"><?php echo $this->translate('Profile') ?></a>
            <a href="<?php echo $this->url('application', array('controller' => 'account', 'action' => 'exit')) ?>"><?php echo $this->translate('Logout') ?></a>
            <?php endif ?>
        </nav>
        <section class='errors <?php if ($messages == null) {echo 'hidden';} ?>'>
            <h2><?php echo $this->translate('Error messages.') ?></h2>
            <ul>
                <?php
                    foreach ($messages as $messageArray)
                    {
                        foreach ($messageArray as $messageContent)
                        {
                            echo '<li>' . $messageContent . '</li>';
                        }
                    }
                ?>
            <ul>
        </section>
        <?php echo $this->content; ?>
        <footer>
            wbondarenko@programmer.net 2015
        </footer>
    </body>
</html>
