<?php
// TODO Externalize labels.

 $title = 'Create person.';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form
 	->setAttribute
 	(
 		'action'
 		, $this->url('application', array('controller' => 'person', 'action' => 'create'))
 	);
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('nameFirst'));
 echo $this->formRow($form->get('nameLast'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();