<?php
	$person = $myself; 
	echo $this->partial('application/person/retrieve', array ('person' => $myself));
?>
<aside>
	<section>
		<h3>Add phone number.</h3>
		<?php
			$phoneNumberCreateForm
				->setAttribute
				(
					'action'
					, $this->url('application', array('controller' => 'phonenumber', 'action' => 'create'))
				);
			$phoneNumberCreateForm->prepare();
			echo $this->form()->openTag($phoneNumberCreateForm);
			echo $this->formRow($phoneNumberCreateForm->get('value'));
			echo $this->formSubmit($phoneNumberCreateForm->get('submit'));
			echo $this->form()->closeTag();
		?>
	</section>
	<section>
		<h3>Add email address.</h3>
		<?php
			$emailAddressCreateForm
				->setAttribute
				(
					'action'
					, $this->url('application', array('controller' => 'emailaddress', 'action' => 'create'))
				);
			$emailAddressCreateForm->prepare();
			echo $this->form()->openTag($emailAddressCreateForm);
			echo $this->formRow($emailAddressCreateForm->get('value'));
			echo $this->formSubmit($emailAddressCreateForm->get('submit'));
			echo $this->form()->closeTag();
		?>
	</section>
	<section>
		<h3>Update credentials.</h3>
		<?php
		  foreach($myself->getCredentials( ) as $credentials)
		  {
				$credentialsUpdateForm
					->setAttribute
					(
						'action'
						, $this->url('application', array('controller' => 'credentials', 'action' => 'update'))
					);
				$credentialsUpdateForm
					->setData
					(
						array
						(
							  'nameFirst' => $credentials->getNameFirst( )
							, 'nameLast' => $credentials->getNameLast( )
						)
					);
				$credentialsUpdateForm->prepare();
				echo $this->form()->openTag($credentialsUpdateForm);
				echo $this->formRow($credentialsUpdateForm->get('nameFirst'));
				echo $this->formRow($credentialsUpdateForm->get('nameLast'));
				echo $this->formSubmit($credentialsUpdateForm->get('submit'));
				echo $this->form()->closeTag();
		  }
		?>
	</section>
</aside>